# Generated by Django 2.2.7 on 2020-02-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0044_require_uri_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog2ExternalDatamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datamodel', models.IntegerField(blank=True)),
                ('catalog', models.ForeignKey(help_text='The catalog which will be used for this project.', on_delete=django.db.models.deletion.CASCADE, related_name='usesDatamodel', to='questions.Catalog', verbose_name='Catalog')),
            ],
            options={
                'unique_together': {('catalog', 'datamodel')},
            },
        ),
    ]
