# Generated by Django 2.2.7 on 2020-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_integration', '0002_auto_20200211_1853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalog2externaldatamodel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='catalog2externaldatamodel',
            constraint=models.UniqueConstraint(fields=('catalog'), name='uniqueCatalog2Model'),
        ),
    ]
