# Generated by Django 2.2.7 on 2020-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_integration', '0003_auto_20200211_1905'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalog2externaldatamodel',
            name='uniqueCatalog2Model',
        ),
        migrations.AddConstraint(
            model_name='catalog2externaldatamodel',
            constraint=models.UniqueConstraint(fields=('catalog',), name='uniqueCatalog2Model'),
        ),
    ]
