# Generated by Django 2.2.7 on 2020-02-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_integration', '0004_auto_20200211_1918'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalog2externaldatamodel',
            name='uniqueCatalog2Model',
        ),
    ]
