# Generated by Django 2.2.7 on 2020-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_integration', '0005_auto_20200211_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog2externaldatamodel',
            name='c',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
