# Generated by Django 2.2.7 on 2020-02-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_integration', '0006_catalog2externaldatamodel_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog2externaldatamodel',
            name='c',
        ),
    ]
