# Generated by Django 2.2.7 on 2020-02-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_integration', '0007_remove_catalog2externaldatamodel_c'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalog2externaldatamodel',
            constraint=models.UniqueConstraint(fields=('catalog',), name='uniqueCatalog2Model'),
        ),
    ]
