# Generated by Django 2.2.7 on 2020-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog2externaldatamodel',
            name='datamodel',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='catalog2externaldatamodel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='catalog2externaldatamodel',
            constraint=models.UniqueConstraint(fields=('catalog',), name='uniqueCatalog2Model'),
        ),
    ]
